Config                      = {}

Config.Locale               = 'en'
Config.Accounts             = { 'bank', 'black_money' }
Config.AccountLabels        = { bank = _U('bank'), black_money = _U('black_money') }
Config.EnableSocietyPayouts = false -- pay from the society account that the player is employed at? Requirement: esx_society
Config.DisableWantedLevel   = true
Config.EnableHud            = false -- enable the default hud? Display current job and accounts (black, bank & cash)
Config.PaycheckInterval     = 15 * 60000
Config.EnableDebug          = false


Config.FoodList = { 
   'bread',
   'hamburger',
  'vodka',
  'water',
  'whisky',
  'wine',
}
Config.DrinkList = { 
   'beer',
   'tequila',
}
Config.DrugList = { 
   'cannabis',
   'cannabis_seed',
   'highgradefemaleseed',
   'highgrademaleseed',
   'highjoint',
   'highqualitybud',
   'cocaine',
   'milk',
   'lowgradefemaleseed',
   'lowgrademaleseseed',
   'averagejoint',
   'averagequalitybud',
   'bagofdope',
   'dopebag',
   'lowqualitybud',
}
Config.SmallBoxList = { 
   'binoculars',
   'highgradefert',
   'lowgradefert',
   'lowjoint',
   'hqdiamond',
   'blowtorch',
   'bobbypin',
   'camera',
   'check',
  'cigarett',
  'contrat',
   'emsgps',
  'engineer',
  'fscanner',
  'goldNecklace',
  'gold_bar',
  'ironBar',
  'goldBar',
  'payDirt',
  'goldNugget',
  'gps',
  'gym_membership',
  'handcuffkeys',
  'hdevice',
  'jewels',
  'joints',
  'lighter',
  'lockpick',
  'origplate',
  'payslip',
  'phone',
  'plate',
  'radardetector',
  'ring',
  'rolex',
  'screwdriver',
  'simcard',
  'VehicleLicense',
  'gps',
  'aluminumFoil',
  'chemistrysupplies',
  'dia_box',
  'drugscales',
  'electronics',
  'fleeca_keycard',
  'hydriodicacid',
  'id_card',
  'ironOxide',
  'hydrogenchloridegas',
  'lyesolution',
  'meth1',
  'meth2',
  'meth3',
  'meth4',
  'miningPan',
  'notepad',
  'plastic',
  'platBar',
  'platinum',
  'pseudoephedrine',
  'purifiedwater',
  'radio',
  'raw_iron',
  'rawDiamond',
  'redphosphorus',
  'rubber',
  'rustyIron',
  'scissors',
  'shovel',
  'wallet',
  'wateringcan',
  'WeaponLicense',
  'wood',
  'zigzag',
  'fish',
  'fishbait',
  'fishingrod',
}
Config.BigBoxList = { 
  'plantpot',
   'airbag',
   'battery',
   'boombox',
   'engineoil',
  'highradio',
  'highrim',
  'laptop',
  'laptop_h',
  'lowradio',
  'miricle_grow',
  'oilfilter',
  'rebuildkit',
  'stockrim',
  'watering_can',
  'glass',
  'soil',
  'thermal_charge',
  'fixkit',
}
Config.AmmoClip = { 
   'PistolClip',
   'SmgClip',
  'ShotgunClip',
  'RifleClip',
  'SniperClip',
}

Config.MeleeList = { 
  'WEAPON_FLASHLIGHT',
  'WEAPON_MACHETE',
  'WEAPON_HATCHET',
  'WEAPON_NIGHTSTICK',
  'WEAPON_BAT',
  'WEAPON_POOLCUE', 
  'WEAPON_MOLOTOV',   
  'WEAPON_KNUCKLE', 
  'WEAPON_KNIFE', 
  'WEAPON_SWITCHBLADE', 
  'WEAPON_FLARE',   
  'WEAPON_PETROLCAN', 
  'WEAPON_WRENCH',
  'WEAPON_BOTTLE',
}
Config.PistolList = { 
  'WEAPON_PISTOL',
  'WEAPON_PISTOL_MK2',
  'WEAPON_COMBATPISTOL',
  'WEAPON_APPISTOL',
  'WEAPON_PISTOL50',
  'WEAPON_SNSPISTOL', 
  'WEAPON_SNSPISTOL_MK2',   
  'WEAPON_HEAVYPISTOL', 
  'WEAPON_VINTAGEPISTOL', 
  'WEAPON_FLAREGUN', 
  'WEAPON_MARKSMANPISTOL',
  'WEAPON_REVOLVER', 
  'WEAPON_REVOLVER_MK2', 
  'WEAPON_DOUBLEACTION', 
  'WEAPON_RAYPISTOL',  
  'WEAPON_CERAMICPISTOL',
  'WEAPON_NAVYREVOLVER',      
}
Config.SmgList = { 
  'WEAPON_MICROSMG',
  'WEAPON_SMG',  
  'WEAPON_SMG_MK2',
  'WEAPON_ASSAULTSMG',
  'WEAPON_COMBATPDW',
  'WEAPON_MACHINEPISTOL',
  'WEAPON_MINISMG',
  'WEAPON_RAYCARBINE',
  'WEAPON_GUSENBERG',
}
Config.ShotgunList = { 
  'WEAPON_PUMPSHOTGUN',
  'WEAPON_PUMPSHOTGUN_MK2',
  'WEAPON_SAWNOFFSHOTGUN',
  'WEAPON_ASSAULTSHOTGUN',
  'WEAPON_BULLPUPSHOTGUN',
  'WEAPON_MUSKET',
  'WEAPON_HEAVYSHOTGUN',
  'WEAPON_DBSHOTGUN',
  'WEAPON_AUTOSHOTGUN',
}
Config.RifleList = { 
  'WEAPON_ASSAULTRIFLE',
  'WEAPON_ASSAULTRIFLE_MK2',
  'WEAPON_CARBINERIFLE',
  'WEAPON_CARBINERIFLE_MK2',
  'WEAPON_ADVANCEDRIFLE',
  'WEAPON_SPECIALCARBINE',
  'WEAPON_SPECIALCARBINE_MK2',
  'WEAPON_BULLPUPRIFLE',
  'WEAPON_BULLPUPRIFLE_MK2',
  'WEAPON_COMPACTRIFLE',
}
Config.SniperList = { 
  'WEAPON_SNIPERRIFLE',
  'WEAPON_HEAVYSNIPER',
  'WEAPON_HEAVYSNIPER_MK2',
  'WEAPON_MARKSMANRIFLE',
  'WEAPON_MARKSMANRIFLE_MK2',
}

Config.SmallList = { 
  'WEAPON_KNIFE', 
  'WEAPON_SWITCHBLADE', 
  'WEAPON_FLARE', 
  'WEAPON_KNUCKLE', 
  'WEAPON_FLASHLIGHT',   
}

Config.RandomList = { 
  'WEAPON_MACHETE',
  'WEAPON_HATCHET',
  'WEAPON_NIGHTSTICK',
  'WEAPON_BAT',
  'WEAPON_POOLCUE', 
  'WEAPON_MOLOTOV',     
  'WEAPON_PETROLCAN', 
}