var tableauQuestion = [
    {   question : "When coming off the highway, you must:",
        propositionA : "Accelerate.",
        propositionB : "Maintain speed.",
        propositionC : "Drift to demonstrate your vehicle control skill.",
        propositionD : "Slow down to the urban areas speed limit.",
        reponse : "D"},

    {   question : "You see a pedestrian crossing the road. You should:",
        propositionA : "Drive straight. They'll move. Or not.",
        propositionB : "Stop, but ram them if they take too long.",
        propositionC : "Stop, and give way to them. Proceed if safe.",
        propositionD : "Shoot the pedestrian if they run their mouth.",
        reponse : "C"},

    {   question : "The speed limits on rural roads are:",
        propositionA : "100 kph.",
        propositionB : "120 kph.",
        propositionC : "80 kph.",
        propositionD : "60 kph.",
        reponse : "A"},

    {   question : "The speed limits on highways are:",
        propositionA : "130 kph.",
        propositionB : "120 kph.",
        propositionC : "110 kph.",
        propositionD : "100 kph.",
        reponse : "A"},


    {   question : "The speed limits on urban roads are:",
        propositionA : "100 kph.",
        propositionB : "80 kph.",
        propositionC : "60 kph.",
        propositionD : "40 kph.",
        reponse : "C"},

  {   question : "You have collided with another vehicle. You should:",
        propositionA : "Drive away screaming.",
        propositionB : "Pull over, assess damage, swap details, and/or call the police and paramedics",
        propositionC : "Open fire with your strap, cyka blat.",
        propositionD : "Run them off the road.",
        reponse : "B"},

  {   question : "Police can instantly seize your licence at the roadside for",
        propositionA : "High-range drink driving offences",
        propositionB : "Dangerous driving, vehicular manslaughter, etc",
        propositionC : "Extremely high range speeding offences",
        propositionD : "All of the above%",
        reponse : "D"},

  {   question : "What should you do when approaching a red traffic light?",
        propositionA : "Treat is as a stop sign and go if it looks safe.",
        propositionB : "Come to a complete stop, wait for green.",
        propositionC : "If turning right, slow down but proceed through.",
        propositionD : "Both A and C",
        reponse : "D"},

  {   question : "Your vehicle has no number plate, you should",
        propositionA : "Not drive it in urban areas",
        propositionB : "Seek permission or escort from police for road transit",
        propositionC : "Expect it to be impounded for driving through the city",
        propositionD : "All of the above",
        reponse : "D"},

  {   question : "You need to park at the bank to get some cash, you should",
        propositionA : "Park right up against the door.",
        propositionB : "Leave it on the road, people will go around",
        propositionC : "Pull over and park against the kerb.",
        propositionD : "Do a 360 reverse drift entry to the parking spot.",
        reponse : "C"},

  {   question : "You come across an accident scene, you should",
        propositionA : "Mind your own business in the hood, homie.",
        propositionB : "Check for injured people, call for help if needed.",
        propositionC : "Notify police if the vehicle is abandoned.",
        propositionD : "Both B and C",
        reponse : "D"},

  {   question : "A vehicle hit yours and is driving off. You should",
        propositionA : "Notify Police of a description and direction",
        propositionB : "Tell nobody. You and your mates will find them.",
        propositionC : "Pursue them at high speeds.",
        propositionD : "Open fire with the strap, CYKA BLAT.",
        reponse : "A"},
]
